spring:
  application:
    name: codeupload
  elasticsearch:
    jest:
      uris: http://172.22.122.24:9200
file:
  index:
    name: rosdb
    type: type_codefile
    rootpath: D:\001-workspace\test\codesearch
    allowfiletype: .java.xml.yml.md