spring:
  application:
    name: codeupload
  elasticsearch:
    jest:
      uris: http://192.168.32.171:9200
file:
  index:
    name: idx_code
    type: type_codefile
    rootpath: D:\00-workspace\ota-upgrade-service
    allowfiletype: .java.xml.yml.md.pem