spring:
  application:
   name: search
  elasticsearch:
    jest:
      uris: http://192.168.32.171:9200
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/
  devtools.restart.enabled: true
file:
  index:
    name: idx_code
    type: type_codefile
server:
  port: 8089
